---
- hosts: localhost
  vars:
    KONG_ADMIN_URL: "http://{{ IPADD }}:8001"
    KONG_JWT: ""
  roles:
    # [START - httpbin-service-get]
    # httpbin-service-get examplehttpbin.com => http://eu.httpbin.org/get
    - role: kong_service
      service:
        name: "httpbin-service-get"
        url: "http://eu.httpbin.org/get"
    - role: kong_route
      route:
        service_name: "httpbin-service-get"
        hosts:
          - "examplehttpbin.com"
    - role: kong_plugins
      plugins:
        service_name: "httpbin-service-get"
        name: "key-auth"
    - role: kong_consumer
      consumer:
        service_name: "httpbin-service-get"
        username: "Jason"
        plugins: "key-auth"
        key: "1234"
    # [END - httpbin-service-get]

    # [START - hello-world-01]
    # hello-world-01 http://hello-world.com/api/v1/employees => http://dummy.restapiexample.com/api/v1/employees
    - role: kong_service
      service:
        name: "hello-world-01"
        url: "http://dummy.restapiexample.com"
    - role: kong_route
      route:
        service_name: "hello-world-01"
        hosts:
          - "hello-world.com"
    - role: kong_plugins
      plugins:
        service_name: "hello-world-01"
        name: "key-auth"
    - role: kong_consumer
      consumer:
        service_name: "hello-world-01"
        username: "Jason"
        plugins: "key-auth"
        key: "1234"
    # [END - hello-world-01]

    # [START - github]
    # github http://custom.github.com/users/puuga => https://api.github.com//users/puuga
    - role: kong_service
      service:
        name: "github"
        url: "https://api.github.com"
    - role: kong_route
      route:
        service_name: "github"
        hosts:
          - "custom.github.com"
    - role: kong_plugins
      plugins:
        service_name: "github"
        name: "key-auth"
    - role: kong_consumer
      consumer:
        service_name: "github"
        username: "Jason"
        plugins: "key-auth"
        key: "1234"
    # [END - github]
  