---
- hosts: localhost
  vars:
    KONG_ADMIN_URL: "http://{{ IPADD }}:8001"
    KONG_JWT: ""
  roles:
    # httpbin-service-get
    - role: kong_service
      service:
        name: "httpbin-service-get"
        url: "http://eu.httpbin.org/get"
    - role: kong_route
      route:
        service_name: "httpbin-service-get"
        hosts:
          - "examplehttpbin.com"
    - role: kong_plugins
      plugins:
        service_name: "httpbin-service-get"
        name: "key-auth"
    - role: kong_consumer
      consumer:
        service_name: "httpbin-service-get"
        username: "Jason"
        plugins: "key-auth"
        key: "1234"
    # hello-world-01
    - role: kong_service
      service:
        name: "hello-world-01"
        url: "https://api.github.com"
    - role: kong_route
      route:
        service_name: "hello-world-01"
        hosts:
          - "hello-world.com"
    - role: kong_plugins
      plugins:
        service_name: "hello-world-01"
        name: "key-auth"
    - role: kong_consumer
      consumer:
        service_name: "hello-world-01"
        username: "Jason"
        plugins: "key-auth"
        key: "1234"
  